import 'jquery'
import 'jquery-ui-dist/jquery-ui.css';
import 'jquery-ui-dist/jquery-ui';
import 'bootstrap';
import '@popperjs/core';
import 'bootstrap/scss/bootstrap.scss';
import '@fortawesome/fontawesome-free/scss/fontawesome.scss';
import './fontawsome.scss';
import './bootstrap.scss';
